apiVersion: v1
kind: Secret
metadata:
  name: microservices-secrets
  namespace: {{ include "microservices.namespace" . }}
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.postgres.credentials.password | b64enc }}
