apiVersion: v1
kind: Secret
metadata:
  name: microservices-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.postgres.credentials.password | b64enc }}
